### ISSUE TITLE
What's the best way to use Carbon in SolidJS in 2023?

### ISSUE THREAD

**Issue by stevesimmons** [mosheduminer/carbon-components-solid#6]
Hi,

Is this project still current? Or are there any newer ports of Carbon?

Thank you!

**Comment by mosheduminer** [comment]
Hi @stevesimmons,

This project stalled (it was too much for me), and is definitely not up to date with carbon. I'm not aware of alternative projects for SolidJS, but maybe you can make use of the web component version of carbon.
